spring:
  datasource:
    url: jdbc:mysql://81.68.224.23:3306/BIDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: remote_user
    password: remote~Ruanshu1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false                # 关闭Hibernate自带SQL打印，避免重复
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    net.ttddyy.dsproxy.listener: DEBUG

# DeepSeek 大语言模型配置
llm:
    api:
      url: https://api.deepseek.com/v1/chat/completions
      key: sk-afd89f34a25f43aba1d8cfe4d6a4a9e5
      model: deepseek-chat  # 可选，默认为deepseek-chat